### PR TITLE
Commit all generated files to git, so dockerhub can build images.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/dockerfiles/17)

### CODE REVIEW

**Comment by nurupo** [comment]
I see a lot of `make -j12` that you probably forgot to change to `make -j$(nproc)`?

**Comment by iphydf** [comment]
Yes, those should be changed, but not in this PR. This PR instantiates the Dockerfile.in templates. Any improvements to those should happen separately.

**Comment by nurupo** [comment]
For Windows x86_64 you might want to install `wine64` package over `wine32`. `WINEARCH=win32` would also need to be changed.

**Comment by nurupo** [comment]
Oh, and I think you wouldn't need `dpkg --add-architecture i386` for `wine64`.

**Comment by nurupo** [comment]
As far as the actual PR change goes, not even sure what to review here. File got generated.

Do we even need to store the generated versions in the repo? Can't whatever runs those Dockerfiles (Travis-CI?) generate them on its own? This somewhat litters the commit history and seems rather unnecessary.

**Comment by nurupo** [comment]
I know that DockerHub is an image repository that you can push locally built Docker images to and pull them back from. Didn't know it provided a service of building images off Docker files on their own machines.

**Comment by nurupo** [comment]
Didn't look into ghc at all, only windows.

**Comment by nurupo** [comment]
Btw, so that you know `CMAKE_CROSSCOMPILING_EMULATOR` used in

```cmake
set(CMAKE_CROSSCOMPILING_EMULATOR "/usr/bin/wine")
```

does nothing until some minor version of CMake 3 at which it was introduced.

Also, qTox [uses](https://github.com/qTox/qTox/blob/4c9b7bfccc36792c9c0ca876727b3e508505774b/windows/cross-compile/build.sh#L1124) it's own [`TEST_CROSSCOMPILING_EMULATOR`](https://github.com/qTox/qTox/blob/4c9b7bfccc36792c9c0ca876727b3e508505774b/cmake/Testing.cmake#L18) for that reason.

**Comment by nurupo** [comment]
[c-toxcore too uses "its own" variable `CROSSCOMPILING_EMULATOR`](https://github.com/qTox/qTox/blob/4c9b7bfccc36792c9c0ca876727b3e508505774b/cmake/Testing.cmake#L18).

**Pull request merged**
